/* helloworld.c generated by valac 0.48.19, the Vala compiler
 * generated from helloworld.vala, do not modify */

/* First Hello world in Vala*/

#include <glib.h>

static void _vala_main (void);

static void
_vala_main (void)
{
	g_print ("Hello world");
}

int
main (int argc,
      char ** argv)
{
	_vala_main ();
	return 0;
}

